### PR TITLE
Abstract surfman and implement glutin

### PR DESCRIPTION
**Pull request by 2e0byo**
Unfortunately I need to rebase this against tao: used feature/tao by mistake.

This PR:
- abstracts the surfman/glutin gl context creation into a new module `gl`
- implements glutin context creation

Glutin runs on my machine, although there is still work to do.  Surfman still crashes, but compiles.

I'll rebase this against tao shortly.

I'm learning rust and feel the use of `cfg` all over the place here is ugly.  I'd appreciate advice on how to tidy it up.

### CODE REVIEW

**Comment by declantsien** [comment]
- > Unfortunately I need to rebase this against tao: used feature/tao by mistake.

My apologies. I force push my changes a lot. Didn't expect PRs. There would be some work rebasing
against tao branch.

- > abstracts the surfman/glutin gl context creation into a new module gl
implements glutin context creation
Glutin runs on my machine, although there is still work to do. Surfman still crashes, but compiles.

I've think about this for GTK glarea too. Now you made it happen first.
BTW, Glutin works on my machine, while surfman is flicking a lot (see video).

https://i.imgur.com/Qy9X3ih.mp4


- > I'll rebase this against tao shortly.

Why are you working against my branch instead of emacs-ng repo? What changes need to be upstream to make you workflow smoother? I would do that. 

- > I'm learning rust and feel the use of cfg all over the place here is ugly. I'd appreciate advice on how to tidy it up.

You got me thinking. Maybe we can do something like this
```
windowing
windowing_impl
```
like folders
```
platform
platform_impl
```
in winit [repo](https://github.com/rust-windowing/winit/tree/master/src) ?

**Comment by declantsien** [comment]
This fixes surfman flicking while keeping glutin works too.
[0001-fix-surfman.patch.txt](https://github.com/declantsien/emacs-ng/files/10781737/0001-fix-surfman.patch.txt)

**Comment by 2e0byo** [comment]
Thanks!

I've not based on this on upstream as the winit/webrender decouple hasn't landed yet.  Additionally Tao is probably the way to go over winit, at least on linux, but I could redo the other PR against upstream if more people want to play with that.

Incidentally I get GL errors when opening a new frame, so that's the next thing to dig into on this fussy machine.

**Comment by 2e0byo** [comment]
> folders

Yes, I think something like that is the way to go, with just one `cfg()` to include the right file in `lib.rs` (since this is a compile-time pick, not runtime).

**Pull request merged**
